### ISSUE TITLE
Downloaded source code doesn't work

### ISSUE THREAD

**Issue by chrisedington** [iamjpg/So-So-Social#4]
Hi,

I don't think the source code I downloaded from Github is working, getting the following error on multiple instances:

The Issue: Feeds don't load, spinner keeps on spinning endlessly.

Console Error:
Uncaught TypeError: Cannot read property 'channel' of undefined -- so.so.social.feed.js:63

http://www.vadev.co.za/sandpit/ctemf/so/ - This is a direct deflation of the ZIP fie.

Please could you confirm this?

Thanks,
Chris

**Comment by chrisedington** [comment]
*\* UPDATE **

The issue is actually when the page is refreshed a few times, the feed stops working. I assume it hits some sort of rate limit from one of the third party services?

Can you confirm this?

Thanks,
Chris

**Comment by iamjpg** [comment]
So, it looks like Twitter changed their RSS API URL. This is now fixed and if you re-download the code the example should work.
